name: 'HelloWorld'

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.2
          cache: npm
      -
        name: Install
        run: npm install
      -
        name: Release and deploy with Dagger
        run: node 00-helloworld/build.mts