name: 'HelloWorld'

on: workflow_dispatch

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.0' 
    - run: go run 00-helloworld/main.go