name: 'HelloWorld'

on: workflow_dispatch

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.2
          cache: npm
          cache-dependency-path: 00-helloworld/package-lock.json
      - name: Install
        run: npm install
        working-directory: ./00-helloworld
      - name: Release and deploy with Dagger
        run: node ./build.mts
        working-directory: ./00-helloworld